export type WonderCategory = 'mindset' | 'wellness' | 'fitness' | 'nutrition' | 'vitamins' | 'lifestyle' | 'calm';
export type WonderType = 'book' | 'video' | 'technique' | 'nutrition-tip' | 'vitamin';

export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack';

export interface Recipe {
  name: string;
  time: string;
  ingredients: string[];
  steps: string[];
}

export interface MealRecipe {
  id: string;
  name: string;
  mealType: MealType;
  thumbnail?: string;
  prepTime: string;
  calories: number;
  protein: string;
  carbs: string;
  fat: string;
  sugar: string;
  difficultyRating: number; // 1-5
  healthRating: number; // 1-5
  healthBenefits: string[];
  ingredients: string[];
  steps: string[];
}

export interface WonderResource {
  id: string;
  title: string;
  description: string;
  category: WonderCategory;
  type: WonderType;
  tags: string[];
  emotionalTone: string;
  goalAlignment: string[];
  content?: string;
  link?: string;
  recipes?: Recipe[];
}

import sparklesIcon from '@/assets/icons/sparkles.png';
import leafIcon from '@/assets/icons/leaf.png';
import dumbbellIcon from '@/assets/icons/dumbbell.png';
import saladIcon from '@/assets/icons/salad.png';
import butterflyIcon from '@/assets/icons/butterfly.png';
import yogaIcon from '@/assets/icons/yoga.png';
import bookIcon from '@/assets/icons/book.png';
import movieIcon from '@/assets/icons/movie.png';
import pillIcon from '@/assets/icons/pill.png';

export const categoryColors: Record<WonderCategory, string> = {
  mindset: '280 70% 60%',
  wellness: '150 55% 50%',
  fitness: '20 85% 55%',
  nutrition: '85 60% 48%',
  vitamins: '45 75% 55%',
  lifestyle: '320 65% 58%',
  calm: '210 60% 55%',
};

export const wonderCategories: { key: WonderCategory; label: string; icon: string }[] = [
  { key: 'mindset', label: 'Mindset & Self-Worth', icon: sparklesIcon },
  { key: 'wellness', label: 'Wellness & Body', icon: leafIcon },
  { key: 'fitness', label: 'Fitness & Movement', icon: dumbbellIcon },
  { key: 'nutrition', label: 'Food & Recipes', icon: saladIcon },
  { key: 'vitamins', label: 'Vitamins & Supplements', icon: pillIcon },
  { key: 'lifestyle', label: 'Lifestyle & Habits', icon: butterflyIcon },
  { key: 'calm', label: 'Calm & Nervous System', icon: yogaIcon },
];

export const typeLabels: Record<WonderType, { label: string; icon: string }> = {
  book: { label: 'Book', icon: bookIcon },
  video: { label: 'Video', icon: movieIcon },
  technique: { label: 'Technique', icon: yogaIcon },
  'nutrition-tip': { label: 'Nutrition Tip', icon: saladIcon },
  vitamin: { label: 'Wellness Tip', icon: pillIcon },
};

export const wonderResources: WonderResource[] = [
  // MINDSET & SELF-WORTH
  {
    id: 'mind-1',
    title: 'The Mountain Meditation',
    description: 'A grounding visualisation to reconnect with your inner stability.',
    category: 'mindset',
    type: 'technique',
    tags: ['grounded', 'calm', 'confidence'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'confidence'],
    content: 'Sit comfortably and close your eyes. Imagine yourself as a mountain — strong, steady, unmovable. Storms may swirl around you, seasons may change, but you remain. Breathe deeply for 5 minutes and feel your roots.',
  },
  {
    id: 'mind-2',
    title: 'You Are a Badass',
    description: 'Jen Sincero\'s guide to ditching self-doubt and embracing your greatness.',
    category: 'mindset',
    type: 'book',
    tags: ['confidence', 'empowerment', 'self-worth'],
    emotionalTone: 'empowering',
    goalAlignment: ['confidence', 'self-worth'],
  },
  {
    id: 'mind-3',
    title: 'Mirror Affirmation Practice',
    description: 'Speak kindly to yourself every morning — 3 affirmations in the mirror.',
    category: 'mindset',
    type: 'technique',
    tags: ['confidence', 'self-love', 'morning'],
    emotionalTone: 'empowering',
    goalAlignment: ['confidence', 'self-worth'],
    content: 'Each morning, look into your own eyes in the mirror. Say three things you love about yourself out loud. Start with "I am..." statements. Notice how it feels. Let it be soft, not forced.',
  },
  {
    id: 'mind-4',
    title: 'The Gifts of Imperfection',
    description: 'Brené Brown on letting go of who you think you should be.',
    category: 'mindset',
    type: 'book',
    tags: ['self-worth', 'vulnerability', 'peace'],
    emotionalTone: 'gentle',
    goalAlignment: ['peace', 'self-worth'],
  },
  {
    id: 'mind-5',
    title: 'Rewriting Your Inner Narrative',
    description: 'Identify and gently transform the stories you tell yourself.',
    category: 'mindset',
    type: 'technique',
    tags: ['self-worth', 'healing', 'clarity'],
    emotionalTone: 'gentle',
    goalAlignment: ['confidence', 'peace'],
    content: 'Write down a belief you hold about yourself that hurts. Now ask: "Is this actually true? Where did this come from?" Then write a kinder version. Repeat weekly.',
  },
  {
    id: 'mind-6',
    title: 'Atomic Habits',
    description: 'James Clear on how tiny changes create remarkable results.',
    category: 'mindset',
    type: 'book',
    tags: ['discipline', 'growth', 'consistency'],
    emotionalTone: 'motivating',
    goalAlignment: ['discipline', 'growth'],
  },
  {
    id: 'mind-7',
    title: 'Future Self Journaling',
    description: 'Write a letter from your dream self to your present self.',
    category: 'mindset',
    type: 'technique',
    tags: ['vision', 'clarity', 'motivation'],
    emotionalTone: 'inspiring',
    goalAlignment: ['confidence', 'growth'],
    content: 'Imagine it\'s one year from now. You\'ve become the version of yourself you dream about. Write a letter from her to you — what does she want you to know? What did she do to get here?',
  },
  {
    id: 'mind-8',
    title: 'The Power of Vulnerability',
    description: 'Brené Brown\'s iconic talk on courage, worthiness, and connection.',
    category: 'mindset',
    type: 'video',
    tags: ['vulnerability', 'courage', 'connection'],
    emotionalTone: 'warm',
    goalAlignment: ['self-worth', 'peace'],
  },

  // WELLNESS & BODY
  {
    id: 'well-1',
    title: 'Morning Lymphatic Dry Brushing',
    description: 'Gentle body brushing to boost circulation and energy.',
    category: 'wellness',
    type: 'technique',
    tags: ['energy', 'glow', 'morning'],
    emotionalTone: 'energising',
    goalAlignment: ['wellness', 'glow'],
    content: 'Use a natural bristle brush before your shower. Start at your feet and brush upward in long, sweeping strokes toward your heart. Spend 3–5 minutes. Your skin will tingle and glow.',
  },
  {
    id: 'well-2',
    title: 'Cold Water Face Splash',
    description: 'An instant pick-me-up for dull mornings — splash ice-cold water on your face.',
    category: 'wellness',
    type: 'technique',
    tags: ['energy', 'glow', 'calm'],
    emotionalTone: 'refreshing',
    goalAlignment: ['wellness', 'energy'],
    content: 'Fill your sink with cold water. Splash your face 10 times. This activates the dive reflex, calms your nervous system, reduces puffiness, and wakes you up gently.',
  },
  {
    id: 'well-3',
    title: 'Sleep Hygiene Ritual',
    description: 'Wind-down techniques for deeper, more restorative sleep.',
    category: 'wellness',
    type: 'technique',
    tags: ['sleep', 'calm', 'restoration'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'wellness'],
    content: '1 hour before bed: dim all lights. 30 min: put phone away. 15 min: gentle stretching or reading. 5 min: slow breathing (4-7-8 pattern). Let your body know it\'s safe to rest.',
  },
  {
    id: 'well-4',
    title: 'The Body Keeps the Score',
    description: 'Bessel van der Kolk explores how trauma lives in the body.',
    category: 'wellness',
    type: 'book',
    tags: ['healing', 'body-awareness', 'peace'],
    emotionalTone: 'deep',
    goalAlignment: ['peace', 'healing'],
  },
  {
    id: 'well-5',
    title: 'Gua Sha Facial Routine',
    description: 'A 5-minute facial tool ritual for depuffing and self-care.',
    category: 'wellness',
    type: 'technique',
    tags: ['glow', 'self-care', 'morning'],
    emotionalTone: 'nurturing',
    goalAlignment: ['glow', 'wellness'],
    content: 'Apply facial oil. Use a gua sha tool in gentle upward strokes along your jawline, cheekbones, and forehead. 5 minutes of intentional care to start or end your day.',
  },
  {
    id: 'well-6',
    title: 'Digital Sunset',
    description: 'Turn off all screens 1 hour before bed for deeper rest.',
    category: 'wellness',
    type: 'technique',
    tags: ['sleep', 'calm', 'boundary'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'discipline'],
    content: 'Set a nightly alarm for your "digital sunset." When it goes off, put all devices in another room. Read, stretch, journal, or simply sit. Your nervous system will thank you.',
  },

  // FITNESS & MOVEMENT
  {
    id: 'fit-1',
    title: '10-Minute Morning Stretch',
    description: 'A gentle full-body stretch to start your day feeling open and alive.',
    category: 'fitness',
    type: 'video',
    tags: ['flexibility', 'morning', 'gentle'],
    emotionalTone: 'calm',
    goalAlignment: ['wellness', 'energy'],
  },
  {
    id: 'fit-2',
    title: 'Walk & Talk Meditation',
    description: 'Combine a gentle walk with positive self-talk or a podcast.',
    category: 'fitness',
    type: 'technique',
    tags: ['movement', 'calm', 'grounded'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'energy'],
    content: 'Take a 20-minute walk with no agenda. Notice five things you can see, four you can hear, three you can feel. Or play a gentle podcast. Let movement and presence blend.',
  },
  {
    id: 'fit-3',
    title: 'Pilates for Posture',
    description: 'Strengthen your core and stand taller with pilates fundamentals.',
    category: 'fitness',
    type: 'video',
    tags: ['strength', 'posture', 'confidence'],
    emotionalTone: 'empowering',
    goalAlignment: ['confidence', 'wellness'],
  },
  {
    id: 'fit-4',
    title: 'Dance It Out',
    description: 'Put on your favourite song and move your body freely for one song.',
    category: 'fitness',
    type: 'technique',
    tags: ['joy', 'energy', 'release'],
    emotionalTone: 'joyful',
    goalAlignment: ['joy', 'energy'],
    content: 'Pick a song that makes you feel alive. Close your door. Dance like nobody\'s watching — because they\'re not. Shake, sway, jump. Let your body express what words can\'t.',
  },
  {
    id: 'fit-5',
    title: '20-Minute Yoga Flow',
    description: 'A calming vinyasa flow to release tension and reconnect.',
    category: 'fitness',
    type: 'video',
    tags: ['flexibility', 'calm', 'strength'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'wellness'],
  },
  {
    id: 'fit-6',
    title: 'Strength Training Basics',
    description: 'Build a foundation with simple, effective movements.',
    category: 'fitness',
    type: 'video',
    tags: ['strength', 'discipline', 'confidence'],
    emotionalTone: 'empowering',
    goalAlignment: ['confidence', 'discipline'],
  },

  // NUTRITION & VITAMINS
  {
    id: 'nutr-1',
    title: 'Morning Lemon Water',
    description: 'Start your day with warm lemon water to support digestion.',
    category: 'nutrition',
    type: 'nutrition-tip',
    tags: ['morning', 'digestion', 'glow'],
    emotionalTone: 'gentle',
    goalAlignment: ['wellness', 'glow'],
    content: 'Squeeze half a lemon into warm (not hot) water. Drink it first thing before breakfast. It supports hydration, digestion, and gives your skin a gentle glow.',
    recipes: [
      {
        name: 'Warm Lemon & Ginger Tonic',
        time: '5 min',
        ingredients: ['½ lemon, juiced', '1 cup warm water', '½ inch fresh ginger, grated', '1 tsp raw honey (optional)'],
        steps: ['Heat water until warm (not boiling).', 'Add lemon juice and grated ginger.', 'Stir in honey if desired.', 'Sip slowly on an empty stomach.'],
      },
      {
        name: 'Lemon Mint Detox Water',
        time: '3 min',
        ingredients: ['1 lemon, sliced', '5-6 fresh mint leaves', '1 litre cold water', 'Ice cubes'],
        steps: ['Add lemon slices and mint to a jug.', 'Fill with cold water and ice.', 'Let it infuse for 10 minutes.', 'Sip throughout the morning.'],
      },
    ],
  },
  {
    id: 'nutr-2',
    title: 'Magnesium for Calm',
    description: 'Magnesium glycinate can help with sleep, anxiety, and muscle tension.',
    category: 'vitamins',
    type: 'vitamin',
    tags: ['calm', 'sleep', 'anxiety'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'wellness'],
    content: 'Magnesium glycinate (200-400mg before bed) may support better sleep and reduced anxiety. Always consult your healthcare provider before starting supplements.',
  },
  {
    id: 'nutr-3',
    title: 'Omega-3 for Brain Health',
    description: 'Support mood and mental clarity with omega-3 fatty acids.',
    category: 'vitamins',
    type: 'vitamin',
    tags: ['clarity', 'mood', 'focus'],
    emotionalTone: 'clear',
    goalAlignment: ['clarity', 'wellness'],
    content: 'Omega-3s from fish oil, flaxseed, or algae supplements support brain function and mood regulation. Aim for foods rich in omega-3s or speak with a provider about supplementation.',
  },
  {
    id: 'nutr-4',
    title: 'Gut-Friendly Foods',
    description: 'Nourish your microbiome with fermented and fibre-rich foods.',
    category: 'nutrition',
    type: 'nutrition-tip',
    tags: ['digestion', 'wellness', 'energy'],
    emotionalTone: 'nurturing',
    goalAlignment: ['wellness', 'energy'],
    content: 'Include yoghurt, kimchi, sauerkraut, or kefir daily. Add fibre from oats, beans, and vegetables. A happy gut means better mood, energy, and skin.',
    recipes: [
      {
        name: 'Probiotic Breakfast Bowl',
        time: '10 min',
        ingredients: ['1 cup Greek yoghurt', '¼ cup granola', '1 tbsp chia seeds', 'Fresh berries', '1 tsp honey', '1 tbsp sauerkraut (on the side)'],
        steps: ['Spoon yoghurt into a bowl.', 'Top with granola, chia seeds, and berries.', 'Drizzle with honey.', 'Enjoy sauerkraut on the side for extra probiotics.'],
      },
      {
        name: 'Gut-Healing Miso Soup',
        time: '15 min',
        ingredients: ['2 cups water', '2 tbsp white miso paste', '½ block soft tofu, cubed', '1 spring onion, sliced', '1 sheet nori, torn', '½ tsp grated ginger'],
        steps: ['Bring water to a gentle simmer (don\'t boil).', 'Dissolve miso paste into the water.', 'Add tofu cubes and ginger.', 'Serve topped with spring onion and nori.'],
      },
    ],
  },
  {
    id: 'nutr-5',
    title: 'Vitamin D & Sunshine',
    description: 'Get 15 minutes of sunlight daily or consider supplementation.',
    category: 'vitamins',
    type: 'vitamin',
    tags: ['energy', 'mood', 'bones'],
    emotionalTone: 'warm',
    goalAlignment: ['energy', 'wellness'],
    content: 'Vitamin D supports mood, immunity, and bone health. Try to get 15 minutes of morning sunlight daily. If you live in a cloudy climate, ask your provider about vitamin D3 supplementation.',
  },
  {
    id: 'nutr-6',
    title: 'Hydration Ritual',
    description: 'Track your water intake with a simple, beautiful habit.',
    category: 'nutrition',
    type: 'nutrition-tip',
    tags: ['hydration', 'glow', 'energy'],
    emotionalTone: 'refreshing',
    goalAlignment: ['glow', 'energy'],
    content: 'Aim for 2 litres of water daily. Get a beautiful water bottle. Add sliced cucumber, mint, or berries for flavour. Set gentle reminders every 2 hours.',
    recipes: [
      {
        name: 'Cucumber Spa Water',
        time: '5 min',
        ingredients: ['½ cucumber, thinly sliced', '1 litre water', '5 fresh mint leaves', '3 slices of lemon'],
        steps: ['Add cucumber, mint, and lemon to a large jar.', 'Fill with filtered water.', 'Refrigerate for 30 min or serve with ice.', 'Refill the jar once — flavour lasts two rounds.'],
      },
      {
        name: 'Berry Glow Infusion',
        time: '5 min',
        ingredients: ['¼ cup mixed berries (strawberry, blueberry, raspberry)', '1 litre sparkling or still water', '2 basil leaves', 'Ice cubes'],
        steps: ['Lightly muddle berries at the bottom of a jug.', 'Add basil and ice.', 'Pour in water and stir gently.', 'Let it sit for 10 minutes, then enjoy.'],
      },
    ],
  },
  {
    id: 'nutr-7',
    title: 'Anti-Inflammatory Eating',
    description: 'Reduce inflammation through colourful, whole foods.',
    category: 'nutrition',
    type: 'nutrition-tip',
    tags: ['wellness', 'healing', 'glow'],
    emotionalTone: 'nurturing',
    goalAlignment: ['wellness', 'healing'],
    content: 'Focus on berries, leafy greens, turmeric, ginger, nuts, and olive oil. Minimise processed foods, refined sugar, and excess alcohol. Your body will feel lighter and more vibrant.',
    recipes: [
      {
        name: 'Golden Turmeric Bowl',
        time: '20 min',
        ingredients: ['1 cup quinoa, cooked', '1 cup roasted sweet potato cubes', '2 cups spinach', '½ avocado, sliced', '1 tbsp olive oil', '½ tsp turmeric', '¼ tsp black pepper', 'Squeeze of lemon'],
        steps: ['Toss sweet potato in olive oil, turmeric, and pepper. Roast at 200°C for 15 min.', 'Build bowl: quinoa base, spinach, roasted sweet potato.', 'Top with avocado slices.', 'Squeeze lemon over everything and enjoy.'],
      },
      {
        name: 'Anti-Inflammatory Smoothie',
        time: '5 min',
        ingredients: ['1 cup frozen mango', '½ banana', '1 tsp turmeric', '1 tbsp ground flaxseed', '1 cup oat milk', '½ tsp cinnamon', 'Pinch of black pepper'],
        steps: ['Add all ingredients to a blender.', 'Blend until smooth and creamy.', 'Pour into a glass and enjoy immediately.', 'Best had in the morning or post-workout.'],
      },
    ],
  },

  // LIFESTYLE & HABITS
  {
    id: 'life-1',
    title: 'The 5-Minute Tidy',
    description: 'Set a timer and tidy one area — a clear space means a clear mind.',
    category: 'lifestyle',
    type: 'technique',
    tags: ['clarity', 'peace', 'discipline'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'discipline'],
    content: 'Set a 5-minute timer. Pick one surface or area (desk, bedside table, kitchen counter). Put everything in its place. Marvel at the calm that follows.',
  },
  {
    id: 'life-2',
    title: 'Sunday Reset Ritual',
    description: 'A weekly practice to prepare your space, mind, and week ahead.',
    category: 'lifestyle',
    type: 'technique',
    tags: ['planning', 'calm', 'intention'],
    emotionalTone: 'nurturing',
    goalAlignment: ['discipline', 'peace'],
    content: 'Every Sunday: tidy your space, do laundry, meal prep something simple, review your week ahead, set 3 intentions. Light a candle. Put on gentle music. Make it feel like a ritual, not a chore.',
  },
  {
    id: 'life-3',
    title: 'Slow Living',
    description: 'Embrace the art of doing less with more intention.',
    category: 'lifestyle',
    type: 'book',
    tags: ['peace', 'intention', 'simplicity'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'simplicity'],
  },
  {
    id: 'life-4',
    title: 'Phone-Free Mornings',
    description: 'Protect the first hour of your day from digital noise.',
    category: 'lifestyle',
    type: 'technique',
    tags: ['boundary', 'morning', 'peace'],
    emotionalTone: 'empowering',
    goalAlignment: ['peace', 'discipline'],
    content: 'For the first 60 minutes after waking, don\'t check your phone. Stretch, make tea, journal, or simply be. You\'ll notice a dramatic shift in how your day feels.',
  },
  {
    id: 'life-5',
    title: 'Gratitude Before Sleep',
    description: 'Name three things you\'re grateful for before closing your eyes.',
    category: 'lifestyle',
    type: 'technique',
    tags: ['gratitude', 'peace', 'sleep'],
    emotionalTone: 'warm',
    goalAlignment: ['peace', 'joy'],
    content: 'Every night before sleep, think of or write down three things you\'re grateful for. They can be tiny. The warmth of your blanket. A kind word. The sunset. Let gratitude be your last thought.',
  },
  {
    id: 'life-6',
    title: 'Capsule Wardrobe Guide',
    description: 'Simplify your wardrobe to feel polished without the stress.',
    category: 'lifestyle',
    type: 'technique',
    tags: ['simplicity', 'confidence', 'intention'],
    emotionalTone: 'empowering',
    goalAlignment: ['confidence', 'simplicity'],
    content: 'Choose 30-40 versatile pieces you love that mix and match. Remove everything else. Getting dressed becomes effortless and joyful instead of stressful.',
  },

  // CALM & NERVOUS SYSTEM
  {
    id: 'calm-1',
    title: '4-7-8 Breathing',
    description: 'A powerful breathing technique to calm anxiety in minutes.',
    category: 'calm',
    type: 'technique',
    tags: ['anxiety', 'calm', 'sleep'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'wellness'],
    content: 'Inhale through your nose for 4 counts. Hold for 7 counts. Exhale through your mouth for 8 counts. Repeat 4 times. This activates your parasympathetic nervous system and calms you down fast.',
  },
  {
    id: 'calm-2',
    title: 'Body Scan Meditation',
    description: 'A gentle practice to release tension you didn\'t know you were holding.',
    category: 'calm',
    type: 'technique',
    tags: ['relaxation', 'body-awareness', 'sleep'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'wellness'],
    content: 'Lie down. Starting from your toes, slowly bring attention to each body part, moving upward. Notice tension without judging it. Breathe into it. Let it soften. Take 10-15 minutes.',
  },
  {
    id: 'calm-3',
    title: 'Vagus Nerve Stimulation',
    description: 'Simple exercises to tone your vagus nerve and reduce stress.',
    category: 'calm',
    type: 'technique',
    tags: ['nervous-system', 'calm', 'healing'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'healing'],
    content: 'Try these: humming for 2 minutes, splashing cold water on your face, slow gargling with water, or placing your hand on your heart and breathing slowly. These stimulate the vagus nerve and signal safety to your body.',
  },
  {
    id: 'calm-4',
    title: 'The Untethered Soul',
    description: 'Michael Singer on freeing yourself from habitual thoughts and emotions.',
    category: 'calm',
    type: 'book',
    tags: ['peace', 'freedom', 'awareness'],
    emotionalTone: 'liberating',
    goalAlignment: ['peace', 'freedom'],
  },
  {
    id: 'calm-5',
    title: '5-4-3-2-1 Grounding',
    description: 'Use your five senses to come back to the present moment.',
    category: 'calm',
    type: 'technique',
    tags: ['anxiety', 'grounded', 'present'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'grounded'],
    content: 'Name 5 things you can see, 4 you can touch, 3 you can hear, 2 you can smell, 1 you can taste. This anchors you in the present and breaks anxiety spirals.',
  },
  {
    id: 'calm-6',
    title: 'Legs Up the Wall',
    description: 'A restorative yoga pose that calms your whole system in 5 minutes.',
    category: 'calm',
    type: 'technique',
    tags: ['relaxation', 'gentle', 'restoration'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'wellness'],
    content: 'Lie on your back and swing your legs up against a wall. Rest here for 5-10 minutes. This simple inversion lowers heart rate, reduces swelling, and calms the nervous system.',
  },
  {
    id: 'calm-7',
    title: 'Journaling for Release',
    description: 'Write without editing to let go of what weighs on you.',
    category: 'calm',
    type: 'technique',
    tags: ['healing', 'release', 'clarity'],
    emotionalTone: 'gentle',
    goalAlignment: ['peace', 'healing'],
    content: 'Set a timer for 10 minutes. Write without stopping, editing, or censoring. Don\'t worry about grammar or making sense. Just let whatever is inside come out onto the page. Then close the journal.',
  },
  {
    id: 'calm-8',
    title: 'Nervous System Reset',
    description: 'A 10-minute guided practice to shift from fight-or-flight to rest-and-digest.',
    category: 'calm',
    type: 'video',
    tags: ['nervous-system', 'calm', 'healing'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'healing'],
  },
];

export const mealRecipes: MealRecipe[] = [
  // BREAKFAST
  {
    id: 'meal-1',
    name: 'Overnight Oats with Berries',
    mealType: 'breakfast',
    prepTime: '10 min + overnight',
    calories: 350,
    protein: '12g',
    carbs: '52g',
    fat: '10g',
    sugar: '14g',
    difficultyRating: 1,
    healthRating: 5,
    healthBenefits: ['High in fibre for gut health', 'Sustained energy from complex carbs', 'Antioxidant-rich berries'],
    ingredients: ['½ cup rolled oats', '½ cup oat milk', '¼ cup Greek yoghurt', '1 tbsp chia seeds', '½ cup mixed berries', '1 tsp honey', 'Pinch of cinnamon'],
    steps: ['Mix oats, milk, yoghurt, chia seeds, and cinnamon in a jar.', 'Refrigerate overnight (or at least 4 hours).', 'Top with berries and honey before eating.', 'Enjoy cold or gently warmed.'],
  },
  {
    id: 'meal-2',
    name: 'Avocado Toast with Poached Egg',
    mealType: 'breakfast',
    prepTime: '15 min',
    calories: 380,
    protein: '14g',
    carbs: '30g',
    fat: '22g',
    sugar: '3g',
    difficultyRating: 2,
    healthRating: 4,
    healthBenefits: ['Healthy fats from avocado', 'Complete protein from egg', 'Good source of vitamin E'],
    ingredients: ['1 slice sourdough bread', '½ ripe avocado', '1 egg', '1 tsp lemon juice', 'Chilli flakes', 'Salt & pepper', 'Microgreens (optional)'],
    steps: ['Toast the sourdough until golden.', 'Mash avocado with lemon juice, salt, and pepper.', 'Poach the egg in simmering water with a splash of vinegar for 3 min.', 'Spread avocado on toast, top with egg, chilli flakes, and microgreens.'],
  },
  {
    id: 'meal-3',
    name: 'Green Smoothie Bowl',
    mealType: 'breakfast',
    prepTime: '8 min',
    calories: 290,
    protein: '8g',
    carbs: '48g',
    fat: '8g',
    sugar: '22g',
    difficultyRating: 1,
    healthRating: 5,
    healthBenefits: ['Packed with vitamins A, C, K', 'Supports immune system', 'Hydrating and detoxifying'],
    ingredients: ['1 frozen banana', '1 cup spinach', '½ cup frozen mango', '½ cup almond milk', '1 tbsp almond butter', 'Toppings: granola, coconut, chia seeds'],
    steps: ['Blend banana, spinach, mango, and almond milk until thick and smooth.', 'Pour into a bowl.', 'Top with granola, coconut, and chia seeds.', 'Eat with a spoon — enjoy slowly!'],
  },
  {
    id: 'meal-4',
    name: 'Probiotic Breakfast Bowl',
    mealType: 'breakfast',
    prepTime: '10 min',
    calories: 310,
    protein: '18g',
    carbs: '38g',
    fat: '9g',
    sugar: '16g',
    difficultyRating: 1,
    healthRating: 5,
    healthBenefits: ['Supports gut microbiome', 'Rich in probiotics and prebiotics', 'High protein for satiety'],
    ingredients: ['1 cup Greek yoghurt', '¼ cup granola', '1 tbsp chia seeds', 'Fresh berries', '1 tsp honey', '1 tbsp sauerkraut (on the side)'],
    steps: ['Spoon yoghurt into a bowl.', 'Top with granola, chia seeds, and berries.', 'Drizzle with honey.', 'Enjoy sauerkraut on the side for extra probiotics.'],
  },

  // LUNCH
  {
    id: 'meal-5',
    name: 'Quinoa Power Bowl',
    mealType: 'lunch',
    prepTime: '25 min',
    calories: 450,
    protein: '16g',
    carbs: '55g',
    fat: '18g',
    sugar: '6g',
    difficultyRating: 2,
    healthRating: 5,
    healthBenefits: ['Complete plant protein from quinoa', 'Anti-inflammatory turmeric', 'High in iron and fibre'],
    ingredients: ['1 cup cooked quinoa', '1 cup roasted sweet potato', '2 cups spinach', '½ avocado', '¼ cup chickpeas', '1 tbsp olive oil', 'Lemon tahini dressing'],
    steps: ['Roast sweet potato cubes at 200°C for 20 min.', 'Build bowl: quinoa base, spinach, sweet potato, chickpeas.', 'Slice avocado on top.', 'Drizzle with lemon tahini dressing.'],
  },
  {
    id: 'meal-6',
    name: 'Mediterranean Wrap',
    mealType: 'lunch',
    prepTime: '15 min',
    calories: 420,
    protein: '14g',
    carbs: '42g',
    fat: '22g',
    sugar: '5g',
    difficultyRating: 1,
    healthRating: 4,
    healthBenefits: ['Heart-healthy olive oil & hummus', 'Rich in antioxidants', 'Good source of fibre'],
    ingredients: ['1 wholemeal wrap', '3 tbsp hummus', '¼ cup feta cheese', 'Cucumber, tomato, red onion sliced', 'Handful of mixed greens', 'Kalamata olives', 'Drizzle of olive oil'],
    steps: ['Spread hummus across the wrap.', 'Layer vegetables, feta, and olives.', 'Drizzle with olive oil.', 'Roll tightly and slice in half.'],
  },
  {
    id: 'meal-7',
    name: 'Gut-Healing Miso Soup',
    mealType: 'lunch',
    prepTime: '15 min',
    calories: 180,
    protein: '12g',
    carbs: '14g',
    fat: '8g',
    sugar: '3g',
    difficultyRating: 2,
    healthRating: 5,
    healthBenefits: ['Fermented miso supports gut bacteria', 'Low calorie and hydrating', 'Anti-inflammatory ginger'],
    ingredients: ['2 cups water', '2 tbsp white miso paste', '½ block soft tofu, cubed', '1 spring onion, sliced', '1 sheet nori, torn', '½ tsp grated ginger'],
    steps: ['Bring water to a gentle simmer (don\'t boil).', 'Dissolve miso paste into the water.', 'Add tofu cubes and ginger.', 'Serve topped with spring onion and nori.'],
  },
  {
    id: 'meal-8',
    name: 'Golden Turmeric Bowl',
    mealType: 'lunch',
    prepTime: '20 min',
    calories: 410,
    protein: '12g',
    carbs: '52g',
    fat: '18g',
    sugar: '8g',
    difficultyRating: 2,
    healthRating: 5,
    healthBenefits: ['Powerful anti-inflammatory effects', 'Rich in vitamins A and C', 'Supports joint and brain health'],
    ingredients: ['1 cup quinoa, cooked', '1 cup roasted sweet potato cubes', '2 cups spinach', '½ avocado, sliced', '1 tbsp olive oil', '½ tsp turmeric', '¼ tsp black pepper', 'Squeeze of lemon'],
    steps: ['Toss sweet potato in olive oil, turmeric, and pepper. Roast at 200°C for 15 min.', 'Build bowl: quinoa base, spinach, roasted sweet potato.', 'Top with avocado slices.', 'Squeeze lemon over everything and enjoy.'],
  },

  // DINNER
  {
    id: 'meal-9',
    name: 'Salmon with Roasted Vegetables',
    mealType: 'dinner',
    prepTime: '30 min',
    calories: 520,
    protein: '35g',
    carbs: '28g',
    fat: '28g',
    sugar: '6g',
    difficultyRating: 3,
    healthRating: 5,
    healthBenefits: ['Omega-3 fatty acids for brain health', 'High quality protein', 'Supports heart health'],
    ingredients: ['1 salmon fillet', '1 cup broccoli florets', '1 cup sweet potato cubes', '1 tbsp olive oil', '1 clove garlic, minced', 'Lemon wedge', 'Fresh dill', 'Salt & pepper'],
    steps: ['Preheat oven to 200°C.', 'Toss vegetables in olive oil, garlic, salt, and pepper. Spread on a baking sheet.', 'Season salmon and place on the sheet. Roast for 20-25 min.', 'Serve with lemon wedge and fresh dill.'],
  },
  {
    id: 'meal-10',
    name: 'Chicken & Veggie Stir-Fry',
    mealType: 'dinner',
    prepTime: '20 min',
    calories: 440,
    protein: '32g',
    carbs: '35g',
    fat: '16g',
    sugar: '8g',
    difficultyRating: 2,
    healthRating: 4,
    healthBenefits: ['Lean protein for muscle recovery', 'Colourful vegetables = diverse nutrients', 'Quick and balanced meal'],
    ingredients: ['200g chicken breast, sliced', '1 cup broccoli', '1 bell pepper, sliced', '1 carrot, julienned', '2 tbsp soy sauce', '1 tbsp sesame oil', '1 tsp ginger, grated', 'Brown rice to serve'],
    steps: ['Cook brown rice according to package instructions.', 'Heat sesame oil in a wok. Stir-fry chicken until golden.', 'Add vegetables and ginger. Cook 3-4 min until tender-crisp.', 'Add soy sauce, toss well. Serve over rice.'],
  },
  {
    id: 'meal-11',
    name: 'Lentil & Vegetable Curry',
    mealType: 'dinner',
    prepTime: '35 min',
    calories: 380,
    protein: '18g',
    carbs: '52g',
    fat: '10g',
    sugar: '8g',
    difficultyRating: 2,
    healthRating: 5,
    healthBenefits: ['Plant-based iron and protein', 'High fibre for digestion', 'Anti-inflammatory spices'],
    ingredients: ['1 cup red lentils', '1 can coconut milk', '1 can diced tomatoes', '1 onion, diced', '2 cloves garlic', '1 tbsp curry powder', '1 tsp turmeric', 'Fresh coriander', 'Basmati rice to serve'],
    steps: ['Sauté onion and garlic until soft.', 'Add curry powder and turmeric, cook 1 min.', 'Add lentils, tomatoes, and coconut milk. Simmer 25 min.', 'Serve over rice with fresh coriander.'],
  },
  {
    id: 'meal-12',
    name: 'Baked Cod with Herb Crust',
    mealType: 'dinner',
    prepTime: '25 min',
    calories: 340,
    protein: '30g',
    carbs: '18g',
    fat: '14g',
    sugar: '2g',
    difficultyRating: 3,
    healthRating: 5,
    healthBenefits: ['Lean white fish high in protein', 'Low calorie and heart-friendly', 'Rich in B vitamins and selenium'],
    ingredients: ['2 cod fillets', '¼ cup breadcrumbs', '2 tbsp fresh parsley, chopped', '1 tbsp olive oil', '1 clove garlic, minced', 'Lemon zest', 'Steamed green beans to serve'],
    steps: ['Preheat oven to 190°C.', 'Mix breadcrumbs, parsley, garlic, lemon zest, and olive oil.', 'Press the herb crust onto the cod fillets.', 'Bake for 15-18 min. Serve with steamed green beans.'],
  },
];
