export type WonderCategory = 'mindset' | 'wellness' | 'fitness' | 'nutrition' | 'vitamins' | 'lifestyle' | 'calm' | 'books';
export type WonderType = 'book' | 'video' | 'technique' | 'nutrition-tip' | 'vitamin';

export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack';
export type FitnessType = 'upper-body' | 'lower-body' | 'core' | 'stretches-yoga' | 'full-body';

export interface Recipe {
  name: string;
  time: string;
  ingredients: string[];
  steps: string[];
}

export interface MealRecipe {
  id: string;
  name: string;
  mealType: MealType;
  thumbnail?: string;
  prepTime: string;
  calories: number;
  protein: string;
  carbs: string;
  fat: string;
  sugar: string;
  difficultyRating: number; // 1-5
  healthRating: number; // 1-5
  healthBenefits: string[];
  ingredients: string[];
  steps: string[];
}

export interface FitnessWorkout {
  id: string;
  name: string;
  fitnessType: FitnessType;
  description: string;
  duration: string;
  calories: number;
  difficulty: number; // 1-5
  intensity: number; // 1-5
  musclesTargeted: string[];
  equipment: string[];
  steps: string[];
  benefits: string[];
}

export interface VitaminDosage {
  amount: string;
  timing: 'morning' | 'evening' | 'with food' | 'morning with food' | 'evening with food' | 'any time with food';
  withFood: boolean;
  notes?: string;
}

export interface WonderResource {
  id: string;
  title: string;
  description: string;
  category: WonderCategory;
  type: WonderType;
  tags: string[];
  emotionalTone: string;
  goalAlignment: string[];
  content?: string;
  link?: string;
  recipes?: Recipe[];
  dosage?: VitaminDosage;
}

import sparklesIcon from '@/assets/icons/sparkles.png';
import leafIcon from '@/assets/icons/leaf.png';
import dumbbellIcon from '@/assets/icons/dumbbell.png';
import saladIcon from '@/assets/icons/salad.png';
import butterflyIcon from '@/assets/icons/butterfly.png';
import yogaIcon from '@/assets/icons/yoga.png';
import bookIcon from '@/assets/icons/book.png';
import movieIcon from '@/assets/icons/movie.png';
import pillIcon from '@/assets/icons/pill.png';

export const categoryColors: Record<WonderCategory, string> = {
  mindset: '280 70% 60%',
  wellness: '150 55% 50%',
  fitness: '20 85% 55%',
  nutrition: '85 60% 48%',
  vitamins: '45 75% 55%',
  lifestyle: '320 65% 58%',
  calm: '210 60% 55%',
  books: '35 80% 50%',
};

export const wonderCategories: { key: WonderCategory; label: string; icon: string }[] = [
  { key: 'mindset', label: 'Mindset & Self-Worth', icon: sparklesIcon },
  { key: 'wellness', label: 'Wellness & Body', icon: leafIcon },
  { key: 'fitness', label: 'Fitness & Movement', icon: dumbbellIcon },
  { key: 'nutrition', label: 'Food & Recipes', icon: saladIcon },
  { key: 'vitamins', label: 'Vitamins & Supplements', icon: pillIcon },
  { key: 'books', label: 'Books', icon: bookIcon },
  { key: 'lifestyle', label: 'Lifestyle & Habits', icon: butterflyIcon },
  { key: 'calm', label: 'Calm & Nervous System', icon: yogaIcon },
];

export const typeLabels: Record<WonderType, { label: string; icon: string }> = {
  book: { label: 'Book', icon: bookIcon },
  video: { label: 'Video', icon: movieIcon },
  technique: { label: 'Technique', icon: yogaIcon },
  'nutrition-tip': { label: 'Nutrition Tip', icon: saladIcon },
  vitamin: { label: 'Wellness Tip', icon: pillIcon },
};

export const wonderResources: WonderResource[] = [
  // MINDSET & SELF-WORTH
  {
    id: 'mind-1',
    title: 'The Mountain Meditation',
    description: 'A grounding visualisation to reconnect with your inner stability.',
    category: 'mindset',
    type: 'technique',
    tags: ['grounded', 'calm', 'confidence'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'confidence'],
    content: 'Sit comfortably and close your eyes. Imagine yourself as a mountain — strong, steady, unmovable. Storms may swirl around you, seasons may change, but you remain. Breathe deeply for 5 minutes and feel your roots.',
  },
  {
    id: 'mind-2',
    title: 'You Are a Badass',
    description: 'Jen Sincero\'s guide to ditching self-doubt and embracing your greatness.',
    category: 'books',
    type: 'book',
    tags: ['confidence', 'empowerment', 'self-worth'],
    emotionalTone: 'empowering',
    goalAlignment: ['confidence', 'self-worth'],
  },
  {
    id: 'mind-3',
    title: 'Mirror Affirmation Practice',
    description: 'Speak kindly to yourself every morning — 3 affirmations in the mirror.',
    category: 'mindset',
    type: 'technique',
    tags: ['confidence', 'self-love', 'morning'],
    emotionalTone: 'empowering',
    goalAlignment: ['confidence', 'self-worth'],
    content: 'Each morning, look into your own eyes in the mirror. Say three things you love about yourself out loud. Start with "I am..." statements. Notice how it feels. Let it be soft, not forced.',
  },
  {
    id: 'mind-4',
    title: 'The Gifts of Imperfection',
    description: 'Brené Brown on letting go of who you think you should be.',
    category: 'books',
    type: 'book',
    tags: ['self-worth', 'vulnerability', 'peace'],
    emotionalTone: 'gentle',
    goalAlignment: ['peace', 'self-worth'],
  },
  {
    id: 'mind-5',
    title: 'Rewriting Your Inner Narrative',
    description: 'Identify and gently transform the stories you tell yourself.',
    category: 'mindset',
    type: 'technique',
    tags: ['self-worth', 'healing', 'clarity'],
    emotionalTone: 'gentle',
    goalAlignment: ['confidence', 'peace'],
    content: 'Write down a belief you hold about yourself that hurts. Now ask: "Is this actually true? Where did this come from?" Then write a kinder version. Repeat weekly.',
  },
  {
    id: 'mind-6',
    title: 'Atomic Habits',
    description: 'James Clear on how tiny changes create remarkable results.',
    category: 'books',
    type: 'book',
    tags: ['discipline', 'growth', 'consistency'],
    emotionalTone: 'motivating',
    goalAlignment: ['discipline', 'growth'],
  },
  {
    id: 'mind-7',
    title: 'Future Self Journaling',
    description: 'Write a letter from your dream self to your present self.',
    category: 'mindset',
    type: 'technique',
    tags: ['vision', 'clarity', 'motivation'],
    emotionalTone: 'inspiring',
    goalAlignment: ['confidence', 'growth'],
    content: 'Imagine it\'s one year from now. You\'ve become the version of yourself you dream about. Write a letter from her to you — what does she want you to know? What did she do to get here?',
  },
  {
    id: 'mind-8',
    title: 'The Power of Vulnerability',
    description: 'Brené Brown\'s iconic talk on courage, worthiness, and connection.',
    category: 'mindset',
    type: 'video',
    tags: ['vulnerability', 'courage', 'connection'],
    emotionalTone: 'warm',
    goalAlignment: ['self-worth', 'peace'],
  },

  // WELLNESS & BODY
  {
    id: 'well-1',
    title: 'Morning Lymphatic Dry Brushing',
    description: 'Gentle body brushing to boost circulation and energy.',
    category: 'wellness',
    type: 'technique',
    tags: ['energy', 'glow', 'morning'],
    emotionalTone: 'energising',
    goalAlignment: ['wellness', 'glow'],
    content: 'Use a natural bristle brush before your shower. Start at your feet and brush upward in long, sweeping strokes toward your heart. Spend 3–5 minutes. Your skin will tingle and glow.',
  },
  {
    id: 'well-2',
    title: 'Cold Water Face Splash',
    description: 'An instant pick-me-up for dull mornings — splash ice-cold water on your face.',
    category: 'wellness',
    type: 'technique',
    tags: ['energy', 'glow', 'calm'],
    emotionalTone: 'refreshing',
    goalAlignment: ['wellness', 'energy'],
    content: 'Fill your sink with cold water. Splash your face 10 times. This activates the dive reflex, calms your nervous system, reduces puffiness, and wakes you up gently.',
  },
  {
    id: 'well-3',
    title: 'Sleep Hygiene Ritual',
    description: 'Wind-down techniques for deeper, more restorative sleep.',
    category: 'wellness',
    type: 'technique',
    tags: ['sleep', 'calm', 'restoration'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'wellness'],
    content: '1 hour before bed: dim all lights. 30 min: put phone away. 15 min: gentle stretching or reading. 5 min: slow breathing (4-7-8 pattern). Let your body know it\'s safe to rest.',
  },
  {
    id: 'well-4',
    title: 'The Body Keeps the Score',
    description: 'Bessel van der Kolk explores how trauma lives in the body.',
    category: 'books',
    type: 'book',
    tags: ['healing', 'body-awareness', 'peace'],
    emotionalTone: 'deep',
    goalAlignment: ['peace', 'healing'],
  },
  {
    id: 'well-5',
    title: 'Gua Sha Facial Routine',
    description: 'A 5-minute facial tool ritual for depuffing and self-care.',
    category: 'wellness',
    type: 'technique',
    tags: ['glow', 'self-care', 'morning'],
    emotionalTone: 'nurturing',
    goalAlignment: ['glow', 'wellness'],
    content: 'Apply facial oil. Use a gua sha tool in gentle upward strokes along your jawline, cheekbones, and forehead. 5 minutes of intentional care to start or end your day.',
  },
  {
    id: 'well-6',
    title: 'Digital Sunset',
    description: 'Turn off all screens 1 hour before bed for deeper rest.',
    category: 'wellness',
    type: 'technique',
    tags: ['sleep', 'calm', 'boundary'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'discipline'],
    content: 'Set a nightly alarm for your "digital sunset." When it goes off, put all devices in another room. Read, stretch, journal, or simply sit. Your nervous system will thank you.',
  },

  // FITNESS & MOVEMENT
  {
    id: 'fit-1',
    title: '10-Minute Morning Stretch',
    description: 'A gentle full-body stretch to start your day feeling open and alive.',
    category: 'fitness',
    type: 'video',
    tags: ['flexibility', 'morning', 'gentle'],
    emotionalTone: 'calm',
    goalAlignment: ['wellness', 'energy'],
  },
  {
    id: 'fit-2',
    title: 'Walk & Talk Meditation',
    description: 'Combine a gentle walk with positive self-talk or a podcast.',
    category: 'fitness',
    type: 'technique',
    tags: ['movement', 'calm', 'grounded'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'energy'],
    content: 'Take a 20-minute walk with no agenda. Notice five things you can see, four you can hear, three you can feel. Or play a gentle podcast. Let movement and presence blend.',
  },
  {
    id: 'fit-3',
    title: 'Pilates for Posture',
    description: 'Strengthen your core and stand taller with pilates fundamentals.',
    category: 'fitness',
    type: 'video',
    tags: ['strength', 'posture', 'confidence'],
    emotionalTone: 'empowering',
    goalAlignment: ['confidence', 'wellness'],
  },
  {
    id: 'fit-4',
    title: 'Dance It Out',
    description: 'Put on your favourite song and move your body freely for one song.',
    category: 'fitness',
    type: 'technique',
    tags: ['joy', 'energy', 'release'],
    emotionalTone: 'joyful',
    goalAlignment: ['joy', 'energy'],
    content: 'Pick a song that makes you feel alive. Close your door. Dance like nobody\'s watching — because they\'re not. Shake, sway, jump. Let your body express what words can\'t.',
  },
  {
    id: 'fit-5',
    title: '20-Minute Yoga Flow',
    description: 'A calming vinyasa flow to release tension and reconnect.',
    category: 'fitness',
    type: 'video',
    tags: ['flexibility', 'calm', 'strength'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'wellness'],
  },
  {
    id: 'fit-6',
    title: 'Strength Training Basics',
    description: 'Build a foundation with simple, effective movements.',
    category: 'fitness',
    type: 'video',
    tags: ['strength', 'discipline', 'confidence'],
    emotionalTone: 'empowering',
    goalAlignment: ['confidence', 'discipline'],
  },

  // NUTRITION & VITAMINS
  {
    id: 'nutr-1',
    title: 'Morning Lemon Water',
    description: 'Start your day with warm lemon water to support digestion.',
    category: 'nutrition',
    type: 'nutrition-tip',
    tags: ['morning', 'digestion', 'glow'],
    emotionalTone: 'gentle',
    goalAlignment: ['wellness', 'glow'],
    content: 'Squeeze half a lemon into warm (not hot) water. Drink it first thing before breakfast. It supports hydration, digestion, and gives your skin a gentle glow.',
    recipes: [
      {
        name: 'Warm Lemon & Ginger Tonic',
        time: '5 min',
        ingredients: ['½ lemon, juiced', '1 cup warm water', '½ inch fresh ginger, grated', '1 tsp raw honey (optional)'],
        steps: ['Heat water until warm (not boiling).', 'Add lemon juice and grated ginger.', 'Stir in honey if desired.', 'Sip slowly on an empty stomach.'],
      },
      {
        name: 'Lemon Mint Detox Water',
        time: '3 min',
        ingredients: ['1 lemon, sliced', '5-6 fresh mint leaves', '1 litre cold water', 'Ice cubes'],
        steps: ['Add lemon slices and mint to a jug.', 'Fill with cold water and ice.', 'Let it infuse for 10 minutes.', 'Sip throughout the morning.'],
      },
    ],
  },
  {
    id: 'nutr-2',
    title: 'Magnesium for Calm',
    description: 'Magnesium glycinate can help with sleep, anxiety, and muscle tension.',
    category: 'vitamins',
    type: 'vitamin',
    tags: ['calm', 'sleep', 'anxiety'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'wellness'],
    content: 'Magnesium glycinate (200-400mg before bed) may support better sleep and reduced anxiety. Always consult your healthcare provider before starting supplements.',
    dosage: { amount: '200–400 mg', timing: 'evening', withFood: false, notes: 'Take 30–60 min before bed for best sleep support' },
  },
  {
    id: 'nutr-3',
    title: 'Omega-3 for Brain Health',
    description: 'Support mood and mental clarity with omega-3 fatty acids.',
    category: 'vitamins',
    type: 'vitamin',
    tags: ['clarity', 'mood', 'focus'],
    emotionalTone: 'clear',
    goalAlignment: ['clarity', 'wellness'],
    content: 'Omega-3s from fish oil, flaxseed, or algae supplements support brain function and mood regulation. Aim for foods rich in omega-3s or speak with a provider about supplementation.',
    dosage: { amount: '1,000–2,000 mg EPA+DHA', timing: 'morning with food', withFood: true, notes: 'Take with a meal containing fat for better absorption' },
  },
  {
    id: 'nutr-4',
    title: 'Gut-Friendly Foods',
    description: 'Nourish your microbiome with fermented and fibre-rich foods.',
    category: 'nutrition',
    type: 'nutrition-tip',
    tags: ['digestion', 'wellness', 'energy'],
    emotionalTone: 'nurturing',
    goalAlignment: ['wellness', 'energy'],
    content: 'Include yoghurt, kimchi, sauerkraut, or kefir daily. Add fibre from oats, beans, and vegetables. A happy gut means better mood, energy, and skin.',
    recipes: [
      {
        name: 'Probiotic Breakfast Bowl',
        time: '10 min',
        ingredients: ['1 cup Greek yoghurt', '¼ cup granola', '1 tbsp chia seeds', 'Fresh berries', '1 tsp honey', '1 tbsp sauerkraut (on the side)'],
        steps: ['Spoon yoghurt into a bowl.', 'Top with granola, chia seeds, and berries.', 'Drizzle with honey.', 'Enjoy sauerkraut on the side for extra probiotics.'],
      },
      {
        name: 'Gut-Healing Miso Soup',
        time: '15 min',
        ingredients: ['2 cups water', '2 tbsp white miso paste', '½ block soft tofu, cubed', '1 spring onion, sliced', '1 sheet nori, torn', '½ tsp grated ginger'],
        steps: ['Bring water to a gentle simmer (don\'t boil).', 'Dissolve miso paste into the water.', 'Add tofu cubes and ginger.', 'Serve topped with spring onion and nori.'],
      },
    ],
  },
  {
    id: 'nutr-5',
    title: 'Vitamin D & Sunshine',
    description: 'Get 15 minutes of sunlight daily or consider supplementation.',
    category: 'vitamins',
    type: 'vitamin',
    tags: ['energy', 'mood', 'bones'],
    emotionalTone: 'warm',
    goalAlignment: ['energy', 'wellness'],
    content: 'Vitamin D supports mood, immunity, and bone health. Try to get 15 minutes of morning sunlight daily. If you live in a cloudy climate, ask your provider about vitamin D3 supplementation.',
    dosage: { amount: '1,000–4,000 IU (D3)', timing: 'morning with food', withFood: true, notes: 'Take with breakfast containing fat; get levels tested first' },
  },
  {
    id: 'nutr-8',
    title: 'Zinc for Immunity',
    description: 'Zinc supports immune function, skin healing, and hormone balance.',
    category: 'vitamins',
    type: 'vitamin',
    tags: ['immunity', 'skin', 'hormones'],
    emotionalTone: 'strong',
    goalAlignment: ['wellness', 'glow'],
    content: 'Zinc plays a crucial role in immune defence, wound healing, and hormone production. Foods rich in zinc include pumpkin seeds, oysters, red meat, and chickpeas. Supplementing with 15-30mg daily (as zinc picolinate) can help if your diet is low. Always take with food to avoid nausea.',
    dosage: { amount: '15–30 mg (zinc picolinate)', timing: 'evening with food', withFood: true, notes: 'Always take with food to avoid nausea; don\'t combine with iron' },
  },
  {
    id: 'nutr-9',
    title: 'B-Complex for Energy',
    description: 'B vitamins fuel your metabolism, mood, and nervous system.',
    category: 'vitamins',
    type: 'vitamin',
    tags: ['energy', 'mood', 'focus'],
    emotionalTone: 'energising',
    goalAlignment: ['energy', 'clarity'],
    content: 'B vitamins (B1, B6, B9, B12) are essential for converting food into energy, supporting brain function, and regulating mood. Leafy greens, eggs, legumes, and fortified foods are great sources. A B-complex supplement can help fill gaps, especially for plant-based diets.',
    dosage: { amount: '1 capsule B-complex', timing: 'morning with food', withFood: true, notes: 'Take in the morning — B vitamins can be energising and may disrupt sleep if taken late' },
  },
  {
    id: 'nutr-10',
    title: 'Probiotics for Gut Health',
    description: 'Support digestion, immunity, and mental clarity with probiotics.',
    category: 'vitamins',
    type: 'vitamin',
    tags: ['digestion', 'immunity', 'mood'],
    emotionalTone: 'nurturing',
    goalAlignment: ['wellness', 'clarity'],
    content: 'Probiotics introduce beneficial bacteria to your gut, supporting digestion, immune function, and even mood regulation via the gut-brain axis. Look for strains like Lactobacillus and Bifidobacterium. Fermented foods (yoghurt, kimchi, kefir) are natural sources, or choose a high-quality supplement with at least 10 billion CFU.',
    dosage: { amount: '10–50 billion CFU', timing: 'morning', withFood: false, notes: 'Take on an empty stomach 30 min before breakfast for best colonisation' },
  },
  {
    id: 'nutr-11',
    title: 'Iron for Vitality',
    description: 'Iron prevents fatigue and supports oxygen transport throughout your body.',
    category: 'vitamins',
    type: 'vitamin',
    tags: ['energy', 'strength', 'wellness'],
    emotionalTone: 'strong',
    goalAlignment: ['energy', 'strength'],
    content: 'Iron is essential for carrying oxygen in your blood and preventing fatigue. Women are especially prone to low iron. Rich sources include spinach, lentils, red meat, and fortified cereals. Pair iron-rich foods with vitamin C (citrus, peppers) to boost absorption. Consult your provider before supplementing.',
    dosage: { amount: '18–27 mg (ferrous bisglycinate)', timing: 'morning', withFood: false, notes: 'Take on empty stomach with vitamin C; avoid with calcium, tea, or coffee' },
  },
  {
    id: 'nutr-12',
    title: 'Collagen for Skin & Joints',
    description: 'Collagen supports glowing skin, strong hair, and joint flexibility.',
    category: 'vitamins',
    type: 'vitamin',
    tags: ['glow', 'skin', 'joints'],
    emotionalTone: 'radiant',
    goalAlignment: ['glow', 'wellness'],
    content: 'Collagen is the most abundant protein in your body, supporting skin elasticity, hair strength, and joint health. Production naturally decreases with age. Hydrolysed collagen peptides (10-15g daily) mixed into coffee, smoothies, or water can help. Pair with vitamin C for better synthesis. Bone broth is a natural source.',
    dosage: { amount: '10–15 g hydrolysed peptides', timing: 'any time with food', withFood: true, notes: 'Mix into coffee, smoothies, or water; pair with vitamin C for better synthesis' },
  },
  {
    id: 'nutr-6',
    title: 'Hydration Ritual',
    description: 'Track your water intake with a simple, beautiful habit.',
    category: 'nutrition',
    type: 'nutrition-tip',
    tags: ['hydration', 'glow', 'energy'],
    emotionalTone: 'refreshing',
    goalAlignment: ['glow', 'energy'],
    content: 'Aim for 2 litres of water daily. Get a beautiful water bottle. Add sliced cucumber, mint, or berries for flavour. Set gentle reminders every 2 hours.',
    recipes: [
      {
        name: 'Cucumber Spa Water',
        time: '5 min',
        ingredients: ['½ cucumber, thinly sliced', '1 litre water', '5 fresh mint leaves', '3 slices of lemon'],
        steps: ['Add cucumber, mint, and lemon to a large jar.', 'Fill with filtered water.', 'Refrigerate for 30 min or serve with ice.', 'Refill the jar once — flavour lasts two rounds.'],
      },
      {
        name: 'Berry Glow Infusion',
        time: '5 min',
        ingredients: ['¼ cup mixed berries (strawberry, blueberry, raspberry)', '1 litre sparkling or still water', '2 basil leaves', 'Ice cubes'],
        steps: ['Lightly muddle berries at the bottom of a jug.', 'Add basil and ice.', 'Pour in water and stir gently.', 'Let it sit for 10 minutes, then enjoy.'],
      },
    ],
  },
  {
    id: 'nutr-7',
    title: 'Anti-Inflammatory Eating',
    description: 'Reduce inflammation through colourful, whole foods.',
    category: 'nutrition',
    type: 'nutrition-tip',
    tags: ['wellness', 'healing', 'glow'],
    emotionalTone: 'nurturing',
    goalAlignment: ['wellness', 'healing'],
    content: 'Focus on berries, leafy greens, turmeric, ginger, nuts, and olive oil. Minimise processed foods, refined sugar, and excess alcohol. Your body will feel lighter and more vibrant.',
    recipes: [
      {
        name: 'Golden Turmeric Bowl',
        time: '20 min',
        ingredients: ['1 cup quinoa, cooked', '1 cup roasted sweet potato cubes', '2 cups spinach', '½ avocado, sliced', '1 tbsp olive oil', '½ tsp turmeric', '¼ tsp black pepper', 'Squeeze of lemon'],
        steps: ['Toss sweet potato in olive oil, turmeric, and pepper. Roast at 200°C for 15 min.', 'Build bowl: quinoa base, spinach, roasted sweet potato.', 'Top with avocado slices.', 'Squeeze lemon over everything and enjoy.'],
      },
      {
        name: 'Anti-Inflammatory Smoothie',
        time: '5 min',
        ingredients: ['1 cup frozen mango', '½ banana', '1 tsp turmeric', '1 tbsp ground flaxseed', '1 cup oat milk', '½ tsp cinnamon', 'Pinch of black pepper'],
        steps: ['Add all ingredients to a blender.', 'Blend until smooth and creamy.', 'Pour into a glass and enjoy immediately.', 'Best had in the morning or post-workout.'],
      },
    ],
  },

  // LIFESTYLE & HABITS
  {
    id: 'life-1',
    title: 'The 5-Minute Tidy',
    description: 'Set a timer and tidy one area — a clear space means a clear mind.',
    category: 'lifestyle',
    type: 'technique',
    tags: ['clarity', 'peace', 'discipline'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'discipline'],
    content: 'Set a 5-minute timer. Pick one surface or area (desk, bedside table, kitchen counter). Put everything in its place. Marvel at the calm that follows.',
  },
  {
    id: 'life-2',
    title: 'Sunday Reset Ritual',
    description: 'A weekly practice to prepare your space, mind, and week ahead.',
    category: 'lifestyle',
    type: 'technique',
    tags: ['planning', 'calm', 'intention'],
    emotionalTone: 'nurturing',
    goalAlignment: ['discipline', 'peace'],
    content: 'Every Sunday: tidy your space, do laundry, meal prep something simple, review your week ahead, set 3 intentions. Light a candle. Put on gentle music. Make it feel like a ritual, not a chore.',
  },
  {
    id: 'life-3',
    title: 'Slow Living',
    description: 'Embrace the art of doing less with more intention.',
    category: 'books',
    type: 'book',
    tags: ['peace', 'intention', 'simplicity'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'simplicity'],
  },
  {
    id: 'life-4',
    title: 'Phone-Free Mornings',
    description: 'Protect the first hour of your day from digital noise.',
    category: 'lifestyle',
    type: 'technique',
    tags: ['boundary', 'morning', 'peace'],
    emotionalTone: 'empowering',
    goalAlignment: ['peace', 'discipline'],
    content: 'For the first 60 minutes after waking, don\'t check your phone. Stretch, make tea, journal, or simply be. You\'ll notice a dramatic shift in how your day feels.',
  },
  {
    id: 'life-5',
    title: 'Gratitude Before Sleep',
    description: 'Name three things you\'re grateful for before closing your eyes.',
    category: 'lifestyle',
    type: 'technique',
    tags: ['gratitude', 'peace', 'sleep'],
    emotionalTone: 'warm',
    goalAlignment: ['peace', 'joy'],
    content: 'Every night before sleep, think of or write down three things you\'re grateful for. They can be tiny. The warmth of your blanket. A kind word. The sunset. Let gratitude be your last thought.',
  },
  {
    id: 'life-6',
    title: 'Capsule Wardrobe Guide',
    description: 'Simplify your wardrobe to feel polished without the stress.',
    category: 'lifestyle',
    type: 'technique',
    tags: ['simplicity', 'confidence', 'intention'],
    emotionalTone: 'empowering',
    goalAlignment: ['confidence', 'simplicity'],
    content: 'Choose 30-40 versatile pieces you love that mix and match. Remove everything else. Getting dressed becomes effortless and joyful instead of stressful.',
  },

  // CALM & NERVOUS SYSTEM
  {
    id: 'calm-1',
    title: '4-7-8 Breathing',
    description: 'A powerful breathing technique to calm anxiety in minutes.',
    category: 'calm',
    type: 'technique',
    tags: ['anxiety', 'calm', 'sleep'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'wellness'],
    content: 'Inhale through your nose for 4 counts. Hold for 7 counts. Exhale through your mouth for 8 counts. Repeat 4 times. This activates your parasympathetic nervous system and calms you down fast.',
  },
  {
    id: 'calm-2',
    title: 'Body Scan Meditation',
    description: 'A gentle practice to release tension you didn\'t know you were holding.',
    category: 'calm',
    type: 'technique',
    tags: ['relaxation', 'body-awareness', 'sleep'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'wellness'],
    content: 'Lie down. Starting from your toes, slowly bring attention to each body part, moving upward. Notice tension without judging it. Breathe into it. Let it soften. Take 10-15 minutes.',
  },
  {
    id: 'calm-3',
    title: 'Vagus Nerve Stimulation',
    description: 'Simple exercises to tone your vagus nerve and reduce stress.',
    category: 'calm',
    type: 'technique',
    tags: ['nervous-system', 'calm', 'healing'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'healing'],
    content: 'Try these: humming for 2 minutes, splashing cold water on your face, slow gargling with water, or placing your hand on your heart and breathing slowly. These stimulate the vagus nerve and signal safety to your body.',
  },
  {
    id: 'calm-4',
    title: 'The Untethered Soul',
    description: 'Michael Singer on freeing yourself from habitual thoughts and emotions.',
    category: 'books',
    type: 'book',
    tags: ['peace', 'freedom', 'awareness'],
    emotionalTone: 'liberating',
    goalAlignment: ['peace', 'freedom'],
  },
  {
    id: 'calm-5',
    title: '5-4-3-2-1 Grounding',
    description: 'Use your five senses to come back to the present moment.',
    category: 'calm',
    type: 'technique',
    tags: ['anxiety', 'grounded', 'present'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'grounded'],
    content: 'Name 5 things you can see, 4 you can touch, 3 you can hear, 2 you can smell, 1 you can taste. This anchors you in the present and breaks anxiety spirals.',
  },
  {
    id: 'calm-6',
    title: 'Legs Up the Wall',
    description: 'A restorative yoga pose that calms your whole system in 5 minutes.',
    category: 'calm',
    type: 'technique',
    tags: ['relaxation', 'gentle', 'restoration'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'wellness'],
    content: 'Lie on your back and swing your legs up against a wall. Rest here for 5-10 minutes. This simple inversion lowers heart rate, reduces swelling, and calms the nervous system.',
  },
  {
    id: 'calm-7',
    title: 'Journaling for Release',
    description: 'Write without editing to let go of what weighs on you.',
    category: 'calm',
    type: 'technique',
    tags: ['healing', 'release', 'clarity'],
    emotionalTone: 'gentle',
    goalAlignment: ['peace', 'healing'],
    content: 'Set a timer for 10 minutes. Write without stopping, editing, or censoring. Don\'t worry about grammar or making sense. Just let whatever is inside come out onto the page. Then close the journal.',
  },
  {
    id: 'calm-8',
    title: 'Nervous System Reset',
    description: 'A 10-minute guided practice to shift from fight-or-flight to rest-and-digest.',
    category: 'calm',
    type: 'video',
    tags: ['nervous-system', 'calm', 'healing'],
    emotionalTone: 'calm',
    goalAlignment: ['peace', 'healing'],
  },
];

export const mealRecipes: MealRecipe[] = [
  // BREAKFAST
  {
    id: 'meal-1',
    name: 'Overnight Oats with Berries',
    mealType: 'breakfast',
    prepTime: '10 min + overnight',
    calories: 350,
    protein: '12g',
    carbs: '52g',
    fat: '10g',
    sugar: '14g',
    difficultyRating: 1,
    healthRating: 5,
    healthBenefits: ['High in fibre for gut health', 'Sustained energy from complex carbs', 'Antioxidant-rich berries'],
    ingredients: ['½ cup rolled oats', '½ cup oat milk', '¼ cup Greek yoghurt', '1 tbsp chia seeds', '½ cup mixed berries', '1 tsp honey', 'Pinch of cinnamon'],
    steps: ['Mix oats, milk, yoghurt, chia seeds, and cinnamon in a jar.', 'Refrigerate overnight (or at least 4 hours).', 'Top with berries and honey before eating.', 'Enjoy cold or gently warmed.'],
  },
  {
    id: 'meal-2',
    name: 'Avocado Toast with Poached Egg',
    mealType: 'breakfast',
    prepTime: '15 min',
    calories: 380,
    protein: '14g',
    carbs: '30g',
    fat: '22g',
    sugar: '3g',
    difficultyRating: 2,
    healthRating: 4,
    healthBenefits: ['Healthy fats from avocado', 'Complete protein from egg', 'Good source of vitamin E'],
    ingredients: ['1 slice sourdough bread', '½ ripe avocado', '1 egg', '1 tsp lemon juice', 'Chilli flakes', 'Salt & pepper', 'Microgreens (optional)'],
    steps: ['Toast the sourdough until golden.', 'Mash avocado with lemon juice, salt, and pepper.', 'Poach the egg in simmering water with a splash of vinegar for 3 min.', 'Spread avocado on toast, top with egg, chilli flakes, and microgreens.'],
  },
  {
    id: 'meal-3',
    name: 'Green Smoothie Bowl',
    mealType: 'breakfast',
    prepTime: '8 min',
    calories: 290,
    protein: '8g',
    carbs: '48g',
    fat: '8g',
    sugar: '22g',
    difficultyRating: 1,
    healthRating: 5,
    healthBenefits: ['Packed with vitamins A, C, K', 'Supports immune system', 'Hydrating and detoxifying'],
    ingredients: ['1 frozen banana', '1 cup spinach', '½ cup frozen mango', '½ cup almond milk', '1 tbsp almond butter', 'Toppings: granola, coconut, chia seeds'],
    steps: ['Blend banana, spinach, mango, and almond milk until thick and smooth.', 'Pour into a bowl.', 'Top with granola, coconut, and chia seeds.', 'Eat with a spoon — enjoy slowly!'],
  },
  {
    id: 'meal-4',
    name: 'Probiotic Breakfast Bowl',
    mealType: 'breakfast',
    prepTime: '10 min',
    calories: 310,
    protein: '18g',
    carbs: '38g',
    fat: '9g',
    sugar: '16g',
    difficultyRating: 1,
    healthRating: 5,
    healthBenefits: ['Supports gut microbiome', 'Rich in probiotics and prebiotics', 'High protein for satiety'],
    ingredients: ['1 cup Greek yoghurt', '¼ cup granola', '1 tbsp chia seeds', 'Fresh berries', '1 tsp honey', '1 tbsp sauerkraut (on the side)'],
    steps: ['Spoon yoghurt into a bowl.', 'Top with granola, chia seeds, and berries.', 'Drizzle with honey.', 'Enjoy sauerkraut on the side for extra probiotics.'],
  },

  // LUNCH
  {
    id: 'meal-5',
    name: 'Quinoa Power Bowl',
    mealType: 'lunch',
    prepTime: '25 min',
    calories: 450,
    protein: '16g',
    carbs: '55g',
    fat: '18g',
    sugar: '6g',
    difficultyRating: 2,
    healthRating: 5,
    healthBenefits: ['Complete plant protein from quinoa', 'Anti-inflammatory turmeric', 'High in iron and fibre'],
    ingredients: ['1 cup cooked quinoa', '1 cup roasted sweet potato', '2 cups spinach', '½ avocado', '¼ cup chickpeas', '1 tbsp olive oil', 'Lemon tahini dressing'],
    steps: ['Roast sweet potato cubes at 200°C for 20 min.', 'Build bowl: quinoa base, spinach, sweet potato, chickpeas.', 'Slice avocado on top.', 'Drizzle with lemon tahini dressing.'],
  },
  {
    id: 'meal-6',
    name: 'Mediterranean Wrap',
    mealType: 'lunch',
    prepTime: '15 min',
    calories: 420,
    protein: '14g',
    carbs: '42g',
    fat: '22g',
    sugar: '5g',
    difficultyRating: 1,
    healthRating: 4,
    healthBenefits: ['Heart-healthy olive oil & hummus', 'Rich in antioxidants', 'Good source of fibre'],
    ingredients: ['1 wholemeal wrap', '3 tbsp hummus', '¼ cup feta cheese', 'Cucumber, tomato, red onion sliced', 'Handful of mixed greens', 'Kalamata olives', 'Drizzle of olive oil'],
    steps: ['Spread hummus across the wrap.', 'Layer vegetables, feta, and olives.', 'Drizzle with olive oil.', 'Roll tightly and slice in half.'],
  },
  {
    id: 'meal-7',
    name: 'Gut-Healing Miso Soup',
    mealType: 'lunch',
    prepTime: '15 min',
    calories: 180,
    protein: '12g',
    carbs: '14g',
    fat: '8g',
    sugar: '3g',
    difficultyRating: 2,
    healthRating: 5,
    healthBenefits: ['Fermented miso supports gut bacteria', 'Low calorie and hydrating', 'Anti-inflammatory ginger'],
    ingredients: ['2 cups water', '2 tbsp white miso paste', '½ block soft tofu, cubed', '1 spring onion, sliced', '1 sheet nori, torn', '½ tsp grated ginger'],
    steps: ['Bring water to a gentle simmer (don\'t boil).', 'Dissolve miso paste into the water.', 'Add tofu cubes and ginger.', 'Serve topped with spring onion and nori.'],
  },
  {
    id: 'meal-8',
    name: 'Golden Turmeric Bowl',
    mealType: 'lunch',
    prepTime: '20 min',
    calories: 410,
    protein: '12g',
    carbs: '52g',
    fat: '18g',
    sugar: '8g',
    difficultyRating: 2,
    healthRating: 5,
    healthBenefits: ['Powerful anti-inflammatory effects', 'Rich in vitamins A and C', 'Supports joint and brain health'],
    ingredients: ['1 cup quinoa, cooked', '1 cup roasted sweet potato cubes', '2 cups spinach', '½ avocado, sliced', '1 tbsp olive oil', '½ tsp turmeric', '¼ tsp black pepper', 'Squeeze of lemon'],
    steps: ['Toss sweet potato in olive oil, turmeric, and pepper. Roast at 200°C for 15 min.', 'Build bowl: quinoa base, spinach, roasted sweet potato.', 'Top with avocado slices.', 'Squeeze lemon over everything and enjoy.'],
  },

  // DINNER
  {
    id: 'meal-9',
    name: 'Salmon with Roasted Vegetables',
    mealType: 'dinner',
    prepTime: '30 min',
    calories: 520,
    protein: '35g',
    carbs: '28g',
    fat: '28g',
    sugar: '6g',
    difficultyRating: 3,
    healthRating: 5,
    healthBenefits: ['Omega-3 fatty acids for brain health', 'High quality protein', 'Supports heart health'],
    ingredients: ['1 salmon fillet', '1 cup broccoli florets', '1 cup sweet potato cubes', '1 tbsp olive oil', '1 clove garlic, minced', 'Lemon wedge', 'Fresh dill', 'Salt & pepper'],
    steps: ['Preheat oven to 200°C.', 'Toss vegetables in olive oil, garlic, salt, and pepper. Spread on a baking sheet.', 'Season salmon and place on the sheet. Roast for 20-25 min.', 'Serve with lemon wedge and fresh dill.'],
  },
  {
    id: 'meal-10',
    name: 'Chicken & Veggie Stir-Fry',
    mealType: 'dinner',
    prepTime: '20 min',
    calories: 440,
    protein: '32g',
    carbs: '35g',
    fat: '16g',
    sugar: '8g',
    difficultyRating: 2,
    healthRating: 4,
    healthBenefits: ['Lean protein for muscle recovery', 'Colourful vegetables = diverse nutrients', 'Quick and balanced meal'],
    ingredients: ['200g chicken breast, sliced', '1 cup broccoli', '1 bell pepper, sliced', '1 carrot, julienned', '2 tbsp soy sauce', '1 tbsp sesame oil', '1 tsp ginger, grated', 'Brown rice to serve'],
    steps: ['Cook brown rice according to package instructions.', 'Heat sesame oil in a wok. Stir-fry chicken until golden.', 'Add vegetables and ginger. Cook 3-4 min until tender-crisp.', 'Add soy sauce, toss well. Serve over rice.'],
  },
  {
    id: 'meal-11',
    name: 'Lentil & Vegetable Curry',
    mealType: 'dinner',
    prepTime: '35 min',
    calories: 380,
    protein: '18g',
    carbs: '52g',
    fat: '10g',
    sugar: '8g',
    difficultyRating: 2,
    healthRating: 5,
    healthBenefits: ['Plant-based iron and protein', 'High fibre for digestion', 'Anti-inflammatory spices'],
    ingredients: ['1 cup red lentils', '1 can coconut milk', '1 can diced tomatoes', '1 onion, diced', '2 cloves garlic', '1 tbsp curry powder', '1 tsp turmeric', 'Fresh coriander', 'Basmati rice to serve'],
    steps: ['Sauté onion and garlic until soft.', 'Add curry powder and turmeric, cook 1 min.', 'Add lentils, tomatoes, and coconut milk. Simmer 25 min.', 'Serve over rice with fresh coriander.'],
  },
  {
    id: 'meal-12',
    name: 'Baked Cod with Herb Crust',
    mealType: 'dinner',
    prepTime: '25 min',
    calories: 340,
    protein: '30g',
    carbs: '18g',
    fat: '14g',
    sugar: '2g',
    difficultyRating: 3,
    healthRating: 5,
    healthBenefits: ['Lean white fish high in protein', 'Low calorie and heart-friendly', 'Rich in B vitamins and selenium'],
    ingredients: ['2 cod fillets', '¼ cup breadcrumbs', '2 tbsp fresh parsley, chopped', '1 tbsp olive oil', '1 clove garlic, minced', 'Lemon zest', 'Steamed green beans to serve'],
    steps: ['Preheat oven to 190°C.', 'Mix breadcrumbs, parsley, garlic, lemon zest, and olive oil.', 'Press the herb crust onto the cod fillets.', 'Bake for 15-18 min. Serve with steamed green beans.'],
  },
  // SNACKS
  {
    id: 'meal-13',
    name: 'Peanut Butter Energy Balls',
    mealType: 'snack',
    prepTime: '15 min',
    calories: 180,
    protein: '6g',
    carbs: '20g',
    fat: '9g',
    sugar: '8g',
    difficultyRating: 1,
    healthRating: 4,
    healthBenefits: ['Quick sustained energy from oats and nut butter', 'No-bake and easy to meal-prep', 'Rich in healthy fats and fibre'],
    ingredients: ['1 cup rolled oats', '½ cup peanut butter', '¼ cup honey', '¼ cup dark chocolate chips', '2 tbsp chia seeds', '1 tsp vanilla extract'],
    steps: ['Mix all ingredients in a bowl until combined.', 'Refrigerate for 20 min until firm.', 'Roll into 12 balls. Store in the fridge for up to a week.'],
  },
  {
    id: 'meal-14',
    name: 'Fresh Fruit & Yogurt Plate',
    mealType: 'snack',
    prepTime: '5 min',
    calories: 150,
    protein: '8g',
    carbs: '22g',
    fat: '3g',
    sugar: '16g',
    difficultyRating: 1,
    healthRating: 5,
    healthBenefits: ['Packed with vitamins and antioxidants', 'Probiotics from yogurt support gut health', 'Hydrating and naturally sweet'],
    ingredients: ['1 cup mixed berries', '½ banana, sliced', '½ cup Greek yogurt', '1 tbsp honey', 'Fresh mint leaves'],
    steps: ['Arrange fruit on a plate.', 'Add a dollop of Greek yogurt on the side.', 'Drizzle with honey and garnish with mint.'],
  },
  {
    id: 'meal-15',
    name: 'Green Detox Smoothie',
    mealType: 'snack',
    prepTime: '5 min',
    calories: 190,
    protein: '5g',
    carbs: '30g',
    fat: '4g',
    sugar: '18g',
    difficultyRating: 1,
    healthRating: 5,
    healthBenefits: ['Loaded with leafy greens and fibre', 'Supports digestion and detoxification', 'Hydrating and vitamin-rich'],
    ingredients: ['1 cup spinach', '½ banana', '½ cup mango chunks', '1 tbsp flax seeds', '1 cup coconut water', 'Juice of ½ lime'],
    steps: ['Add all ingredients to a blender.', 'Blend on high for 60 seconds until smooth.', 'Pour into a glass and enjoy immediately.'],
  },
  {
    id: 'meal-16',
    name: 'Hummus & Veggie Sticks',
    mealType: 'snack',
    prepTime: '10 min',
    calories: 160,
    protein: '6g',
    carbs: '18g',
    fat: '7g',
    sugar: '4g',
    difficultyRating: 1,
    healthRating: 5,
    healthBenefits: ['High in plant protein and fibre', 'Anti-inflammatory chickpea base', 'Low-calorie, nutrient-dense snacking'],
    ingredients: ['½ cup hummus', '1 carrot, cut into sticks', '1 cucumber, cut into sticks', '1 bell pepper, sliced', '6 cherry tomatoes'],
    steps: ['Wash and cut vegetables into sticks.', 'Arrange around a bowl of hummus.', 'Dip and enjoy!'],
  },
];

export const fitnessWorkouts: FitnessWorkout[] = [
  // UPPER BODY
  {
    id: 'fw-1',
    name: 'Toned Arms Sculpt',
    fitnessType: 'upper-body',
    description: 'Sculpt lean, defined arms with this targeted upper-body routine.',
    duration: '15 min',
    calories: 90,
    difficulty: 2,
    intensity: 3,
    musclesTargeted: ['Biceps', 'Triceps', 'Shoulders'],
    equipment: ['Light dumbbells (2-5 lbs)', 'Mat'],
    steps: ['Warm up with arm circles (1 min each direction).', 'Bicep curls — 3 sets of 12 reps.', 'Tricep dips on a chair — 3 sets of 10.', 'Shoulder press — 3 sets of 10.', 'Lateral raises — 3 sets of 12.', 'Cool down with gentle arm stretches.'],
    benefits: ['Builds lean muscle definition', 'Improves posture and shoulder stability', 'Boosts metabolism'],
  },
  {
    id: 'fw-2',
    name: 'Push-Up Power',
    fitnessType: 'upper-body',
    description: 'Master push-up variations to build chest and shoulder strength.',
    duration: '12 min',
    calories: 120,
    difficulty: 3,
    intensity: 4,
    musclesTargeted: ['Chest', 'Shoulders', 'Triceps', 'Core'],
    equipment: ['Mat'],
    steps: ['Start with 10 standard push-ups.', 'Wide-grip push-ups — 8 reps.', 'Diamond push-ups — 8 reps.', 'Incline push-ups on a step — 10 reps.', 'Negative push-ups (slow lower) — 6 reps.', 'Rest 30 sec between sets. Repeat circuit twice.'],
    benefits: ['Builds functional upper body strength', 'No equipment needed', 'Strengthens core stability'],
  },
  {
    id: 'fw-3',
    name: 'Back & Posture Fix',
    fitnessType: 'upper-body',
    description: 'Strengthen your back to improve posture and reduce tension.',
    duration: '18 min',
    calories: 100,
    difficulty: 2,
    intensity: 3,
    musclesTargeted: ['Upper back', 'Lats', 'Rear deltoids'],
    equipment: ['Resistance band', 'Mat'],
    steps: ['Band pull-aparts — 3 sets of 15.', 'Bent-over rows with band — 3 sets of 12.', 'Prone Y-raises — 3 sets of 10.', 'Superman holds — 3 sets of 20 sec.', 'Cat-cow stretch cool down — 1 min.'],
    benefits: ['Corrects rounded shoulders', 'Reduces back and neck pain', 'Improves confidence through better posture'],
  },
  {
    id: 'fw-4',
    name: 'Resistance Band Arms',
    fitnessType: 'upper-body',
    description: 'A gentle yet effective arm workout using only a resistance band.',
    duration: '14 min',
    calories: 70,
    difficulty: 1,
    intensity: 2,
    musclesTargeted: ['Biceps', 'Triceps', 'Forearms'],
    equipment: ['Resistance band'],
    steps: ['Band bicep curls — 3 sets of 15.', 'Overhead tricep extensions — 3 sets of 12.', 'Band pull-aparts — 3 sets of 15.', 'Wrist curls — 2 sets of 15.', 'Stretch and release.'],
    benefits: ['Joint-friendly resistance training', 'Perfect for travel or home', 'Builds toned arms gradually'],
  },

  // LOWER BODY
  {
    id: 'fw-5',
    name: 'Glute Bridge Burn',
    fitnessType: 'lower-body',
    description: 'Activate and strengthen your glutes with targeted bridge variations.',
    duration: '15 min',
    calories: 85,
    difficulty: 2,
    intensity: 3,
    musclesTargeted: ['Glutes', 'Hamstrings', 'Lower back'],
    equipment: ['Mat', 'Optional resistance band'],
    steps: ['Basic glute bridges — 3 sets of 15.', 'Single-leg bridges — 3 sets of 10 each side.', 'Banded bridge holds — 3 sets of 20 sec.', 'Frog pumps — 2 sets of 20.', 'Hip flexor stretch — 30 sec each side.'],
    benefits: ['Reduces lower back pain', 'Shapes and lifts glutes', 'Improves hip mobility'],
  },
  {
    id: 'fw-6',
    name: 'Squat & Lunge Circuit',
    fitnessType: 'lower-body',
    description: 'Build strong legs with this squat and lunge combination workout.',
    duration: '20 min',
    calories: 180,
    difficulty: 3,
    intensity: 4,
    musclesTargeted: ['Quads', 'Glutes', 'Hamstrings', 'Calves'],
    equipment: ['Mat', 'Optional dumbbells'],
    steps: ['Bodyweight squats — 15 reps.', 'Forward lunges — 12 each leg.', 'Sumo squats — 15 reps.', 'Reverse lunges — 12 each leg.', 'Wall sit — 45 sec.', 'Repeat circuit twice with 1 min rest.'],
    benefits: ['Builds lower body strength', 'Burns significant calories', 'Improves balance and coordination'],
  },
  {
    id: 'fw-7',
    name: 'Inner Thigh Toner',
    fitnessType: 'lower-body',
    description: 'Target your inner thighs with pilates-inspired movements.',
    duration: '12 min',
    calories: 75,
    difficulty: 2,
    intensity: 2,
    musclesTargeted: ['Inner thighs', 'Hip adductors', 'Core'],
    equipment: ['Mat', 'Small pilates ball (optional)'],
    steps: ['Side-lying inner thigh lifts — 20 each side.', 'Sumo squat pulses — 3 sets of 15.', 'Ball squeeze (or pillow) — 3 sets of 15.', 'Cossack squats — 8 each side.', 'Butterfly stretch — 1 min.'],
    benefits: ['Tones hard-to-reach muscles', 'Improves hip flexibility', 'Supports knee stability'],
  },
  {
    id: 'fw-8',
    name: 'Calf & Ankle Strength',
    fitnessType: 'lower-body',
    description: 'Strengthen calves and ankles for better balance and stability.',
    duration: '10 min',
    calories: 60,
    difficulty: 1,
    intensity: 2,
    musclesTargeted: ['Calves', 'Ankles', 'Feet'],
    equipment: ['Mat', 'Step or stair'],
    steps: ['Standing calf raises — 3 sets of 20.', 'Single-leg calf raises — 3 sets of 12 each.', 'Ankle circles — 15 each direction per foot.', 'Toe walks — 1 min.', 'Heel walks — 1 min.'],
    benefits: ['Prevents ankle injuries', 'Improves balance for heels', 'Supports running and walking'],
  },

  // CORE
  {
    id: 'fw-9',
    name: 'Pilates Core Burn',
    fitnessType: 'core',
    description: 'A pilates-inspired core routine for a strong, sculpted midsection.',
    duration: '15 min',
    calories: 110,
    difficulty: 3,
    intensity: 3,
    musclesTargeted: ['Abs', 'Obliques', 'Deep core'],
    equipment: ['Mat'],
    steps: ['The Hundred — 100 pumps.', 'Roll-ups — 10 reps.', 'Single-leg stretch — 10 each side.', 'Criss-cross — 10 each side.', 'Plank hold — 45 sec.', 'Side plank — 30 sec each side.'],
    benefits: ['Flattens and tones the stomach', 'Improves spinal support', 'Better posture throughout the day'],
  },
  {
    id: 'fw-10',
    name: 'Plank Challenge',
    fitnessType: 'core',
    description: 'Progressive plank variations to build endurance and core stability.',
    duration: '10 min',
    calories: 95,
    difficulty: 3,
    intensity: 4,
    musclesTargeted: ['Core', 'Shoulders', 'Back'],
    equipment: ['Mat'],
    steps: ['Standard plank — 30 sec.', 'Forearm plank — 30 sec.', 'Side plank left — 20 sec.', 'Side plank right — 20 sec.', 'Plank shoulder taps — 20 reps.', 'Plank up-downs — 10 reps.', 'Rest 30 sec, repeat twice.'],
    benefits: ['Builds full-body stability', 'Strengthens without crunching', 'Improves mental endurance'],
  },
  {
    id: 'fw-11',
    name: 'Gentle Ab Toning',
    fitnessType: 'core',
    description: 'A softer core workout perfect for beginners or recovery days.',
    duration: '12 min',
    calories: 65,
    difficulty: 1,
    intensity: 2,
    musclesTargeted: ['Lower abs', 'Transverse abdominis'],
    equipment: ['Mat'],
    steps: ['Dead bugs — 10 each side.', 'Pelvic tilts — 15 reps.', 'Leg slides — 10 each side.', 'Bird dogs — 10 each side.', 'Gentle twist — 8 each side.', 'Deep breathing cool down — 1 min.'],
    benefits: ['Safe for beginners and postnatal', 'Activates deep stabilizers', 'Reduces lower back discomfort'],
  },
  {
    id: 'fw-12',
    name: 'Oblique Sculptor',
    fitnessType: 'core',
    description: 'Define your waistline with targeted oblique exercises.',
    duration: '14 min',
    calories: 100,
    difficulty: 2,
    intensity: 3,
    musclesTargeted: ['Obliques', 'Serratus', 'Hip flexors'],
    equipment: ['Mat', 'Optional dumbbell'],
    steps: ['Side crunches — 15 each side.', 'Bicycle crunches — 20 total.', 'Russian twists — 20 total.', 'Standing side bends — 15 each side.', 'Woodchops — 12 each side.', 'Side plank dips — 10 each side.'],
    benefits: ['Creates defined waistline', 'Improves rotational strength', 'Helps with sports and daily movement'],
  },

  // STRETCHES & YOGA
  {
    id: 'fw-13',
    name: 'Morning Sun Salutation',
    fitnessType: 'stretches-yoga',
    description: 'Wake up your body with this classic yoga flow sequence.',
    duration: '10 min',
    calories: 70,
    difficulty: 1,
    intensity: 2,
    musclesTargeted: ['Full body', 'Spine', 'Hamstrings'],
    equipment: ['Mat'],
    steps: ['Mountain pose — 5 breaths.', 'Forward fold — hold 5 breaths.', 'Halfway lift — 3 breaths.', 'Low lunge right — 5 breaths.', 'Downward dog — 5 breaths.', 'Low lunge left — 5 breaths.', 'Return to standing. Repeat 3 times.'],
    benefits: ['Energizes without caffeine', 'Improves flexibility over time', 'Sets a calm, intentional tone for the day'],
  },
  {
    id: 'fw-14',
    name: 'Hip Opener Flow',
    fitnessType: 'stretches-yoga',
    description: 'Release deep tension stored in your hips with this gentle flow.',
    duration: '15 min',
    calories: 60,
    difficulty: 2,
    intensity: 1,
    musclesTargeted: ['Hip flexors', 'Glutes', 'Inner thighs'],
    equipment: ['Mat', 'Yoga block (optional)'],
    steps: ['Butterfly pose — 1 min.', 'Low lunge with twist — 1 min each side.', 'Pigeon pose — 1 min each side.', 'Happy baby — 1 min.', 'Reclined bound angle — 2 min.', 'Savasana — 2 min.'],
    benefits: ['Releases emotional tension held in hips', 'Reduces sciatica and lower back pain', 'Improves range of motion'],
  },
  {
    id: 'fw-15',
    name: 'Bedtime Stretch Ritual',
    fitnessType: 'stretches-yoga',
    description: 'A soothing stretch sequence to prepare your body for restful sleep.',
    duration: '12 min',
    calories: 45,
    difficulty: 1,
    intensity: 1,
    musclesTargeted: ['Neck', 'Shoulders', 'Spine', 'Hamstrings'],
    equipment: ['Mat or bed'],
    steps: ['Neck rolls — 1 min.', 'Seated forward fold — 1 min.', 'Supine twist — 1 min each side.', 'Legs up the wall — 3 min.', 'Child\'s pose — 2 min.', 'Final relaxation with deep breathing — 2 min.'],
    benefits: ['Activates parasympathetic nervous system', 'Releases day\'s tension from body', 'Improves sleep quality naturally'],
  },
  {
    id: 'fw-16',
    name: 'Deep Flexibility Flow',
    fitnessType: 'stretches-yoga',
    description: 'A slow, deep stretch session for increasing overall flexibility.',
    duration: '25 min',
    calories: 80,
    difficulty: 2,
    intensity: 1,
    musclesTargeted: ['Hamstrings', 'Spine', 'Shoulders', 'Hips'],
    equipment: ['Mat', 'Strap or towel'],
    steps: ['Standing forward fold — 1 min.', 'Wide-legged fold — 1 min.', 'Seated straddle — 2 min.', 'Seated hamstring stretch — 1 min each side.', 'Thread the needle — 1 min each side.', 'Reclining hand-to-big-toe — 1 min each.', 'Final savasana — 3 min.'],
    benefits: ['Gradually increases flexibility', 'Reduces muscle soreness', 'Promotes mindfulness and body awareness'],
  },

  // FULL BODY
  {
    id: 'fw-17',
    name: '20-Min Total Body Burn',
    fitnessType: 'full-body',
    description: 'A high-energy circuit hitting every major muscle group in 20 minutes.',
    duration: '20 min',
    calories: 220,
    difficulty: 3,
    intensity: 4,
    musclesTargeted: ['Full body', 'Legs', 'Arms', 'Core'],
    equipment: ['Mat', 'Optional dumbbells'],
    steps: ['Jumping jacks warm-up — 1 min.', 'Squats — 15 reps.', 'Push-ups — 10 reps.', 'Lunges — 12 each leg.', 'Plank hold — 30 sec.', 'Burpees — 8 reps.', 'Mountain climbers — 20 reps.', 'Bicycle crunches — 20 reps.', 'Rest 1 min, repeat circuit twice.', 'Cool-down stretches — 2 min.'],
    benefits: ['Maximum calorie burn in minimal time', 'Builds functional full-body strength', 'Boosts cardiovascular fitness'],
  },
  {
    id: 'fw-18',
    name: 'Beginner Full Body Flow',
    fitnessType: 'full-body',
    description: 'A gentle introduction to full-body training with simple, effective moves.',
    duration: '15 min',
    calories: 90,
    difficulty: 1,
    intensity: 2,
    musclesTargeted: ['Full body', 'Core', 'Legs', 'Arms'],
    equipment: ['Mat'],
    steps: ['March in place — 1 min.', 'Wall push-ups — 10 reps.', 'Bodyweight squats — 12 reps.', 'Standing knee raises — 10 each side.', 'Bird dogs — 8 each side.', 'Glute bridges — 12 reps.', 'Arm circles — 30 sec each direction.', 'Gentle full-body stretch — 2 min.'],
    benefits: ['Perfect starting point for fitness beginners', 'Low impact on joints', 'Builds confidence and movement patterns'],
  },
  {
    id: 'fw-19',
    name: 'Dumbbell Sculpt Session',
    fitnessType: 'full-body',
    description: 'A structured dumbbell workout to tone and strengthen your entire body.',
    duration: '25 min',
    calories: 200,
    difficulty: 3,
    intensity: 3,
    musclesTargeted: ['Shoulders', 'Back', 'Chest', 'Legs', 'Core'],
    equipment: ['Dumbbells (5-15 lbs)', 'Mat'],
    steps: ['Dumbbell squats — 3 sets of 12.', 'Dumbbell rows — 3 sets of 10 each arm.', 'Overhead press — 3 sets of 10.', 'Romanian deadlifts — 3 sets of 12.', 'Chest press on floor — 3 sets of 10.', 'Weighted crunches — 3 sets of 15.', 'Cool-down stretches — 3 min.'],
    benefits: ['Builds lean muscle definition everywhere', 'Increases bone density', 'Efficient compound movements'],
  },
  {
    id: 'fw-20',
    name: 'No-Equipment HIIT',
    fitnessType: 'full-body',
    description: 'An intense bodyweight HIIT session you can do anywhere, no gear needed.',
    duration: '18 min',
    calories: 280,
    difficulty: 4,
    intensity: 5,
    musclesTargeted: ['Full body', 'Cardio', 'Core', 'Legs'],
    equipment: ['None'],
    steps: ['High knees — 30 sec.', 'Rest — 15 sec.', 'Squat jumps — 30 sec.', 'Rest — 15 sec.', 'Push-up to shoulder tap — 30 sec.', 'Rest — 15 sec.', 'Lunge jumps — 30 sec.', 'Rest — 15 sec.', 'Plank jacks — 30 sec.', 'Rest — 15 sec.', 'Repeat circuit 3 times.', 'Walking cool-down — 2 min.'],
    benefits: ['Burns calories for hours after workout', 'No equipment or gym needed', 'Improves speed and agility'],
  },
];
