project_id = "dgyynvfzoepjhcpjpdbs"

[functions.generate-home-messages]
verify_jwt = false

[functions.generate-habit-icon]
verify_jwt = false

[functions.wonder-recommendations]
verify_jwt = false

[functions.ubi-chat]
verify_jwt = false
